name: Build Android App

on:
  # 当推送到主分支时触发
  push:
    branches: [ master ]
  # 当创建pull request时触发
  pull_request:
    branches: [ master ]
  # 允许手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v5
    
    # 设置JDK环境
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
        cache: gradle
    
    # 设置Android SDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    # 确保gradlew有执行权限
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    # 构建Debug版本
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    # 构建Release版本
    - name: Build Release APK
      run: ./gradlew assembleRelease
    
    
    # 上传Debug APK
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    
    # 上传Release APK
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
    
    # 上传混淆映射文件
    - name: Upload Release Mapping File
      uses: actions/upload-artifact@v4
      with:
        name: mapping-file
        path: app/build/outputs/mapping/release/mapping.txt
